### ISSUE TITLE
ndnSIM-NLSR configuration file

### ISSUE THREAD

**Issue by campuszh** [3rd-ndn-hackathon/ndnSIM-NLSR#2]
Hi,
I was trying to run ndn-nlsr-simple.cpp (under src/ndnSIM/example directory) by using " ./waf --run=ndn-nlsr-simple "and there is a error occurred:
`Failed to read configuration file: src/ndnSIM/examples/ndn-nlsr-conf/nlsr_node_N0.conf
Failed to read configuration file: src/ndnSIM/examples/ndn-nlsr-conf/nlsr_node_N1.conf
Failed to read configuration file: src/ndnSIM/examples/ndn-nlsr-conf/nlsr_node_N2.conf
Failed to read configuration file: src/ndnSIM/examples/ndn-nlsr-conf/nlsr_node_N3.conf
Failed to read configuration file: src/ndnSIM/examples/ndn-nlsr-conf/nlsr_node_N4.conf
`
can anyone tell me how to solve this problem? Thanks

**Comment by anilj1** [comment]
Did you run the confgen utility first to generate the topology and node
configuration files?

/anil.

**Comment by campuszh** [comment]
No,after ./waf configure and ./waf,i just run the ndn-nlsr-simple.cpp to testing if nlsr can work.Should i run confgen utility before run ndn-nlsr-simple ? And how can i do to run confgen ?
Thanks for your reply.

**Comment by anilj1** [comment]
Hi,

Follow this link for all the steps.

https://github.com/3rd-ndn-hackathon/ndnSIM-NLSR/blob/master/PORTING.md

/anil.

**Comment by campuszh** [comment]
Thanks very much for your help, i have successfully installed it.

**Comment by campuszh** [comment]
dfsdf
